---
apiVersion: v1
kind: Secret
metadata:
  name: hpg01-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-aro24/hpg01-gateway-gitops
